openapi: 3.0.0
info:
  title: Example API
  description: A simple API to demonstrate Swagger UI
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /:
    get:
      summary: "Hello World"
      description: "Returns a simple hello world message"
      responses:
        '200':
          description: "A hello world response"
          content:
            text/plain:
              schema:
                type: string
                example: "Hello world!"
