openapi: 3.0.0
info:
  title: Sample API
  description: API doc
  version: 1.0.0
paths:
  /:
    get:
      summary: Returns a greeting
      responses:
        '200':
          description: Greeting response
          content:
            application/json:
              schema:
                type: string
                example: Hello world!
